# Generated by Django 6.0.4 on 2026-06-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraising", "0002_djangohero_approved_booleanfield"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="djangohero",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_customer_id", ""), _negated=True),
                fields=("stripe_customer_id",),
                name="unique_nonblank_djangohero_stripe_customer_id",
            ),
        ),
    ]
